CREATE TABLE IF NOT EXISTS ordenes_compra (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    codigo_compra VARCHAR(40) NOT NULL,
    fecha DATE NOT NULL,
    empleado_id BIGINT UNSIGNED NULL,
    empleado_nombre VARCHAR(180) NULL,
    proveedor_id BIGINT UNSIGNED NOT NULL,
    proveedor_label VARCHAR(180) NULL,
    proveedor_rnc VARCHAR(20) NULL,
    condicion_pago VARCHAR(50) NULL,
    comentario TEXT NULL,
    subtotal DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
    total_descuento DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
    descuento_general_pct DECIMAL(8,2) NOT NULL DEFAULT 0.00,
    impuesto DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
    total_compra DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
    moneda VARCHAR(10) NOT NULL DEFAULT 'DOP',
    estado VARCHAR(20) NOT NULL DEFAULT 'abierta',
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_oc_codigo (codigo_compra),
    KEY idx_oc_fecha (fecha),
    KEY idx_oc_proveedor (proveedor_id),
    KEY idx_oc_estado (estado),
    KEY idx_oc_created_by (created_by),
    KEY idx_oc_updated_by (updated_by),
    CONSTRAINT fk_oc_proveedor FOREIGN KEY (proveedor_id) REFERENCES proveedores(id) ON DELETE RESTRICT,
    CONSTRAINT fk_oc_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_oc_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ordenes_compra_detalles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    orden_compra_id BIGINT UNSIGNED NOT NULL,
    articulo_id BIGINT UNSIGNED NULL,
    codigo VARCHAR(80) NULL,
    descripcion VARCHAR(255) NULL,
    cantidad DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
    unidad VARCHAR(20) NULL,
    cant_por_unidad DECIMAL(18,4) NULL,
    peso_por_unidad DECIMAL(18,4) NULL,
    peso_unidad VARCHAR(10) NULL,
    costo DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
    desc_pct DECIMAL(8,2) NOT NULL DEFAULT 0.00,
    impuesto_pct DECIMAL(8,2) NOT NULL DEFAULT 0.00,
    total DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_ocd_orden (orden_compra_id),
    KEY idx_ocd_articulo (articulo_id),
    CONSTRAINT fk_ocd_oc FOREIGN KEY (orden_compra_id) REFERENCES ordenes_compra(id) ON DELETE CASCADE,
    CONSTRAINT fk_ocd_articulo FOREIGN KEY (articulo_id) REFERENCES articulos(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
