CREATE TABLE IF NOT EXISTS secuencias (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    clave VARCHAR(50) NOT NULL,
    aplica_a VARCHAR(80) NOT NULL DEFAULT 'Otros',
    prefijo VARCHAR(20) NOT NULL DEFAULT '',
    longitud INT NOT NULL DEFAULT 8,
    valor_actual BIGINT NOT NULL DEFAULT 0,
    incremento INT NOT NULL DEFAULT 1,
    activo TINYINT(1) NOT NULL DEFAULT 1,
    uso_total BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_secuencias_clave (clave)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
