CREATE TABLE IF NOT EXISTS articulos_costo_historial (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    articulo_id BIGINT UNSIGNED NOT NULL,
    proveedor_id BIGINT UNSIGNED NOT NULL,
    entrada_compra_id BIGINT UNSIGNED NULL,
    orden_compra_id BIGINT UNSIGNED NULL,
    fecha DATE NOT NULL,
    cantidad DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
    unidad VARCHAR(20) NULL,
    cant_por_unidad DECIMAL(18,4) NULL,
    peso_por_unidad DECIMAL(18,4) NULL,
    peso_unidad VARCHAR(10) NULL,
    total_kg DECIMAL(18,6) NULL,
    costo_unitario DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
    moneda VARCHAR(10) NOT NULL DEFAULT 'DOP',
    total_linea DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_ach_articulo (articulo_id),
    KEY idx_ach_proveedor (proveedor_id),
    KEY idx_ach_fecha (fecha),
    KEY idx_ach_entrada (entrada_compra_id),
    KEY idx_ach_oc (orden_compra_id),
    CONSTRAINT fk_ach_articulo FOREIGN KEY (articulo_id) REFERENCES articulos(id) ON DELETE RESTRICT,
    CONSTRAINT fk_ach_proveedor FOREIGN KEY (proveedor_id) REFERENCES proveedores(id) ON DELETE RESTRICT,
    CONSTRAINT fk_ach_entrada FOREIGN KEY (entrada_compra_id) REFERENCES entradas_compra(id) ON DELETE SET NULL,
    CONSTRAINT fk_ach_oc FOREIGN KEY (orden_compra_id) REFERENCES ordenes_compra(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
