CREATE TABLE IF NOT EXISTS pedidos (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    codigo_pedido VARCHAR(50) NOT NULL,
    fecha DATE NOT NULL,
    cliente_id BIGINT UNSIGNED NOT NULL,
    cliente_nombre VARCHAR(150) NOT NULL,
    cliente_telefono VARCHAR(50) NULL,
    cliente_rnc VARCHAR(50) NULL,
    localidad_id BIGINT UNSIGNED NULL,
    localidad_nombre VARCHAR(150) NULL,
    empleado_id BIGINT UNSIGNED NULL,
    empleado_nombre VARCHAR(150) NULL,
    orden_no VARCHAR(50) NULL,
    comentario TEXT NULL,
    departamento ENUM('almacen', 'facturacion') NOT NULL DEFAULT 'almacen',
    visto TINYINT(1) NOT NULL DEFAULT 0,
    subtotal DECIMAL(18,4) NOT NULL DEFAULT 0,
    total DECIMAL(18,4) NOT NULL DEFAULT 0,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_pedidos_codigo (codigo_pedido),
    KEY idx_pedidos_cliente (cliente_id),
    CONSTRAINT fk_pedidos_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id),
    CONSTRAINT fk_pedidos_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_pedidos_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS pedido_detalles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    pedido_id BIGINT UNSIGNED NOT NULL,
    articulo_id BIGINT UNSIGNED NOT NULL,
    presentacion_id BIGINT UNSIGNED NOT NULL,
    empaque_id BIGINT UNSIGNED NOT NULL,
    cantidad DECIMAL(18,0) NOT NULL,
    precio DECIMAL(18,4) NOT NULL,
    descuento_pct DECIMAL(5,2) NOT NULL DEFAULT 0,
    descuento_monto DECIMAL(18,4) NOT NULL DEFAULT 0,
    total DECIMAL(18,4) NOT NULL,
    articulo_codigo VARCHAR(50) NOT NULL,
    articulo_descripcion VARCHAR(200) NOT NULL,
    presentacion_descripcion VARCHAR(100) NOT NULL,
    empaque_descripcion VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    KEY idx_pedido_detalles_pedido (pedido_id),
    KEY idx_pedido_detalles_articulo (articulo_id),
    CONSTRAINT fk_pedido_detalles_pedido FOREIGN KEY (pedido_id) REFERENCES pedidos(id) ON DELETE CASCADE,
    CONSTRAINT fk_pedido_detalles_articulo FOREIGN KEY (articulo_id) REFERENCES articulos(id)
);
