CREATE TABLE IF NOT EXISTS entradas_compra (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    codigo_entrada VARCHAR(40) NOT NULL,
    fecha DATE NOT NULL,
    empleado_id BIGINT UNSIGNED NULL,
    empleado_nombre VARCHAR(180) NULL,
    proveedor_id BIGINT UNSIGNED NOT NULL,
    proveedor_label VARCHAR(180) NULL,
    proveedor_rnc VARCHAR(20) NULL,
    condicion_pago VARCHAR(50) NULL,
    ncf VARCHAR(30) NULL,
    orden_no VARCHAR(40) NULL,
    factura_no VARCHAR(40) NULL,
    pedido_no VARCHAR(40) NULL,
    comentario TEXT NULL,
    subtotal DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
    total_descuento DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
    descuento_general_pct DECIMAL(8,2) NOT NULL DEFAULT 0.00,
    impuesto DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
    total_compra DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
    moneda VARCHAR(10) NOT NULL DEFAULT 'DOP',
    estado VARCHAR(20) NOT NULL DEFAULT 'abierta',
    orden_compra_id BIGINT UNSIGNED NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_ec_codigo (codigo_entrada),
    KEY idx_ec_fecha (fecha),
    KEY idx_ec_proveedor (proveedor_id),
    KEY idx_ec_estado (estado),
    KEY idx_ec_oc (orden_compra_id),
    KEY idx_ec_created_by (created_by),
    KEY idx_ec_updated_by (updated_by),
    CONSTRAINT fk_ec_proveedor FOREIGN KEY (proveedor_id) REFERENCES proveedores(id) ON DELETE RESTRICT,
    CONSTRAINT fk_ec_oc FOREIGN KEY (orden_compra_id) REFERENCES ordenes_compra(id) ON DELETE SET NULL,
    CONSTRAINT fk_ec_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_ec_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS entradas_compra_detalles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    entrada_compra_id BIGINT UNSIGNED NOT NULL,
    orden_compra_detalle_id BIGINT UNSIGNED NULL,
    articulo_id BIGINT UNSIGNED NULL,
    codigo VARCHAR(80) NULL,
    descripcion VARCHAR(255) NULL,
    cantidad DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
    unidad VARCHAR(20) NULL,
    cant_por_unidad DECIMAL(18,4) NULL,
    peso_por_unidad DECIMAL(18,4) NULL,
    peso_unidad VARCHAR(10) NULL,
    costo DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
    desc_pct DECIMAL(8,2) NOT NULL DEFAULT 0.00,
    impuesto_pct DECIMAL(8,2) NOT NULL DEFAULT 0.00,
    total DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_ecd_entrada (entrada_compra_id),
    KEY idx_ecd_oc_detalle (orden_compra_detalle_id),
    KEY idx_ecd_articulo (articulo_id),
    CONSTRAINT fk_ecd_entrada FOREIGN KEY (entrada_compra_id) REFERENCES entradas_compra(id) ON DELETE CASCADE,
    CONSTRAINT fk_ecd_oc_detalle FOREIGN KEY (orden_compra_detalle_id) REFERENCES ordenes_compra_detalles(id) ON DELETE SET NULL,
    CONSTRAINT fk_ecd_articulo FOREIGN KEY (articulo_id) REFERENCES articulos(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
