CREATE TABLE IF NOT EXISTS proveedores (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    razon_social VARCHAR(180) NOT NULL,
    nombre_comercial VARCHAR(180) NULL,
    rnc VARCHAR(20) NULL,
    cedula VARCHAR(20) NULL,
    tipo_proveedor VARCHAR(80) NULL,
    estado VARCHAR(30) NULL,
    correo VARCHAR(150) NULL,
    telefono VARCHAR(40) NULL,
    telefono_secundario VARCHAR(40) NULL,
    whatsapp VARCHAR(40) NULL,
    contacto_nombre VARCHAR(150) NULL,
    contacto_telefono VARCHAR(40) NULL,
    contacto_email VARCHAR(150) NULL,
    contacto_cargo VARCHAR(100) NULL,
    direccion VARCHAR(250) NULL,
    ciudad VARCHAR(100) NULL,
    provincia VARCHAR(100) NULL,
    pais VARCHAR(100) NULL,
    codigo_postal VARCHAR(20) NULL,
    condicion_pago VARCHAR(80) NULL,
    dias_credito INT NOT NULL DEFAULT 0,
    limite_credito DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    balance_actual DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    moneda VARCHAR(10) NOT NULL DEFAULT 'DOP',
    banco VARCHAR(120) NULL,
    tipo_banco VARCHAR(40) NULL,
    tipo_cuenta VARCHAR(60) NULL,
    numero_cuenta VARCHAR(60) NULL,
    titular_cuenta VARCHAR(160) NULL,
    rnc_titular VARCHAR(20) NULL,
    cuenta_contable VARCHAR(80) NULL,
    tipo_gasto VARCHAR(80) NULL,
    retencion_itbis DECIMAL(8,2) NOT NULL DEFAULT 0.00,
    retencion_isr DECIMAL(8,2) NOT NULL DEFAULT 0.00,
    aplica_impuestos TINYINT(1) NOT NULL DEFAULT 0,
    categoria_proveedor VARCHAR(100) NULL,
    rubro VARCHAR(120) NULL,
    tiempo_entrega VARCHAR(80) NULL,
    calificacion VARCHAR(40) NULL,
    observaciones TEXT NULL,
    contrato VARCHAR(255) NULL,
    documento_rnc VARCHAR(255) NULL,
    documento_identidad VARCHAR(255) NULL,
    otros_documentos VARCHAR(255) NULL,
    recibir_ordenes_correo TINYINT(1) NOT NULL DEFAULT 0,
    recibir_pagos_correo TINYINT(1) NOT NULL DEFAULT 0,
    correos_notificacion TEXT NULL,
    inactivo TINYINT(1) NOT NULL DEFAULT 0,
    fecha_inactivo DATE NULL,
    motivo_inactivo VARCHAR(255) NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_proveedores_created_by (created_by),
    KEY idx_proveedores_updated_by (updated_by),
    CONSTRAINT fk_proveedores_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_proveedores_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
