CREATE TABLE IF NOT EXISTS clientes (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    razon_social VARCHAR(180) NOT NULL,
    nombre_comercial VARCHAR(180) NULL,
    rnc VARCHAR(20) NULL,
    cedula VARCHAR(20) NULL,
    tipo_cliente VARCHAR(30) NOT NULL DEFAULT 'empresa',
    tipo_ncf_preferido VARCHAR(60) NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'activo',
    nombre_contacto VARCHAR(150) NULL,
    cargo_contacto VARCHAR(100) NULL,
    telefono_cliente VARCHAR(40) NULL,
    telefono_secundario VARCHAR(40) NULL,
    whatsapp VARCHAR(40) NULL,
    correo_electronico VARCHAR(150) NULL,
    correo_facturacion VARCHAR(150) NULL,
    direccion VARCHAR(250) NULL,
    ciudad VARCHAR(100) NULL,
    provincia VARCHAR(100) NULL,
    pais VARCHAR(100) NULL,
    codigo_postal VARCHAR(20) NULL,
    condicion_pago VARCHAR(20) NOT NULL DEFAULT 'contado',
    dias_credito INT NOT NULL DEFAULT 0,
    limite_credito DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    balance_actual DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    moneda VARCHAR(10) NOT NULL DEFAULT 'DOP',
    descuento_default DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    vendedor_asignado VARCHAR(120) NULL,
    canal_venta VARCHAR(50) NULL,
    tipo_comprobante_preferido VARCHAR(60) NULL,
    secuencia_asignada VARCHAR(60) NULL,
    aplica_itbis TINYINT(1) NOT NULL DEFAULT 1,
    exento_itbis TINYINT(1) NOT NULL DEFAULT 0,
    retencion_aplica TINYINT(1) NOT NULL DEFAULT 0,
    agente_retencion TINYINT(1) NOT NULL DEFAULT 0,
    banco_cliente VARCHAR(150) NULL,
    numero_cuenta_cliente VARCHAR(60) NULL,
    tipo_cuenta_cliente VARCHAR(30) NULL,
    tipo_negocio VARCHAR(100) NULL,
    sector VARCHAR(100) NULL,
    categoria_cliente VARCHAR(100) NULL,
    prioridad VARCHAR(20) NULL,
    calificacion VARCHAR(40) NULL,
    recibir_factura_correo TINYINT(1) NOT NULL DEFAULT 1,
    recibir_estado_cuenta TINYINT(1) NOT NULL DEFAULT 0,
    correos_notificacion_adicional VARCHAR(255) NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_clientes_created_by (created_by),
    KEY idx_clientes_updated_by (updated_by),
    KEY idx_clientes_razon_social (razon_social),
    KEY idx_clientes_estado (estado),
    CONSTRAINT fk_clientes_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_clientes_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
