CREATE TABLE IF NOT EXISTS cotizaciones (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    codigo_cotizacion VARCHAR(50) NOT NULL,
    fecha DATE NOT NULL,
    fecha_vencimiento DATE NULL,
    validez_dias INT NOT NULL DEFAULT 0,
    estado VARCHAR(30) NOT NULL DEFAULT 'borrador',
    moneda VARCHAR(10) NOT NULL DEFAULT 'DOP',
    cliente_id BIGINT UNSIGNED NOT NULL,
    cliente_nombre VARCHAR(150) NOT NULL,
    cliente_telefono VARCHAR(50) NULL,
    cliente_rnc VARCHAR(50) NULL,
    localidad_id BIGINT UNSIGNED NULL,
    localidad_nombre VARCHAR(150) NULL,
    empleado_id BIGINT UNSIGNED NULL,
    empleado_nombre VARCHAR(150) NULL,
    comentario TEXT NULL,
    condiciones TEXT NULL,
    subtotal DECIMAL(18,4) NOT NULL DEFAULT 0,
    descuento_lineas DECIMAL(18,4) NOT NULL DEFAULT 0,
    descuento_general_pct DECIMAL(5,2) NOT NULL DEFAULT 0,
    descuento_general_monto DECIMAL(18,4) NOT NULL DEFAULT 0,
    impuesto_pct DECIMAL(5,2) NOT NULL DEFAULT 0,
    impuesto DECIMAL(18,4) NOT NULL DEFAULT 0,
    total DECIMAL(18,4) NOT NULL DEFAULT 0,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_cotizaciones_codigo (codigo_cotizacion),
    KEY idx_cotizaciones_cliente (cliente_id),
    CONSTRAINT fk_cotizaciones_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id),
    CONSTRAINT fk_cotizaciones_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_cotizaciones_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS cotizacion_detalles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    cotizacion_id BIGINT UNSIGNED NOT NULL,
    articulo_id BIGINT UNSIGNED NOT NULL,
    presentacion_id BIGINT UNSIGNED NOT NULL,
    empaque_id BIGINT UNSIGNED NOT NULL,
    cantidad DECIMAL(18,0) NOT NULL,
    precio DECIMAL(18,4) NOT NULL,
    descuento_pct DECIMAL(5,2) NOT NULL DEFAULT 0,
    descuento_monto DECIMAL(18,4) NOT NULL DEFAULT 0,
    total DECIMAL(18,4) NOT NULL,
    articulo_codigo VARCHAR(50) NOT NULL,
    articulo_descripcion VARCHAR(200) NOT NULL,
    presentacion_descripcion VARCHAR(100) NOT NULL,
    empaque_descripcion VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    KEY idx_cotizacion_detalles_cotizacion (cotizacion_id),
    KEY idx_cotizacion_detalles_articulo (articulo_id),
    CONSTRAINT fk_cotizacion_detalles_cotizacion FOREIGN KEY (cotizacion_id) REFERENCES cotizaciones(id) ON DELETE CASCADE,
    CONSTRAINT fk_cotizacion_detalles_articulo FOREIGN KEY (articulo_id) REFERENCES articulos(id)
);
